### ISSUE TITLE
ICLABEL fails: Input signal X must be a double-precision vector

### ISSUE THREAD

**Issue by arnodelorme** [sccn/ICLabel#11]
Copied from https://github.com/sccn/eeglab/issues/200

ICLABEL aborts with the message “The input signal X must be a double-precision vector., (Error occurred in function validateinput() at line 101)”. ICLABEL 1.2.6 installed. The EEGLAB preference for single precision is NOT checked. Using a 64-bit PC. SASICA runs without difficulty. Problem seems to be unique to my installation/configuration: When I take the same dataset to a friend’s lab, ICLABEL runs without problems.

**Comment by lucapton** [comment]
@arnodelorme I'm unfamiliar with the function `validateinput`. It's not part of ICLabel and I didn't get any results when searching EEGLAB's repo. Do you know where it's from?

@AlanAHartley Do you have more information to share on this error? I'd be helpful to have the error that printed out on the screen. If you used the EEGLAB GUI, you can get the error by running iclabel through the GUI (if you haven't recently) and then typing `eegh` in the command window. That will print out all the command line calls to recreate what was done through the GUI. You can then copy and paste the call to `iclabel` that you see there to get the error to print to the screen.

**Comment by arnodelorme** [comment]
@AlanAHartley  would you mind to type "which validateinput" and let us know the result? thank you

**Comment by AlanAHartley** [comment]
Arnaud:  It’s actually a MATLAB error message. I’ll do the things you suggested. I have learned more, though. I have been using SOBI for ICA. If I instead use RUNICA then ICLABEL runs without difficulty!  Go figure!  Alan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AlanAHartley** [comment]
Arnaud:

I neglected to paste in the eeglab history you asked for:

>> eegh
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Pos3a_10_FiSg.set','filepath','D:\\C from Optiplex\\EEG\\EEGLAB\\Positivity 3 Filtered & Segmented Data\\Pos3a EEGLAB Segmented\\');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );

Alan
________________________________

**Comment by lucapton** [comment]
Alan, you have to run the commands in the EEGLAB GUI in order to see it in the `eegh` output and then you'd have to run the command to see the actual error.

Anyhow, it sounds like it a compatibility issue with SOBI. I'm glad you found a workaround.

**Comment by AlanAHartley** [comment]
Hi Luca,

Thank you for your response.  Here’s what I did (which I think is what you said):

In the command window, I launched EEGLAB.
In the GUI: File—>Load Existing Dataset (that I knew would cause the error).
In the GUI: Tools—>ICLABEL—>Label Components.  [Produces error]
In the command window: eegh

Best,
Alan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
