### ISSUE TITLE
Original weights for usage with tensorflow?

### ISSUE THREAD

**Issue by marcpabst** [sccn/ICLabel#12]
Hi, this looks pretty cool. Since I typically avoid using MATLAB, I was wondering if iI could use the trained classifier with TensorFlow directly. Since original training was done using Python, I assume the data might already (still?) exists in a TensorFlow-readable format. If this is the case, any way you could share it?

**Comment by lucapton** [comment]
While it does exist somewhere, it's not packaged for easy sharing at the moment. I suggest using it through EEGLAB for now. I'll see if I can get it into exportable form at some point, but no promises.
