### ISSUE TITLE
SASICA_1.3.7 Error

### ISSUE THREAD

**Issue by yangumikang** [sccn/ICLabel#13]
Hello,

I am new to eeglab and trying to pre-process my data set. When I tried to run SASICA, the newest version available, it gave me the following error. I greatly appreciate it if anyone can give me some advice to solve this issue. Or even alternative plugins that do similar function as SASICA.

Thank you,
Yangmi
================================
ERROR. Please send the entire error log below to max.chaumon@gmail.com. Thanks for your help!
================================
This is SASICA_1.3.7
This is MATLAB 9.9.0.1467703 (R2020b)
Running on MACI64
MARA:
  enable: 0
FASTER:
  enable: 0
  blinkchanname: No channel
ADJUST:
  enable: 0
chancorr:
  enable: 0
  channames: No channel
  corthresh: auto 4
EOGcorr:
  enable: 0
  Heogchannames: No channel
  corthreshH: auto 4
  Veogchannames: No channel
  corthreshV: auto 4
resvar:
  enable: 0
  thresh: 15
SNR:
  enable: 0
  snrcut: 1
  snrBL: -Inf    0
  snrPOI: 0  Inf
trialfoc:
  enable: 0
  focaltrialout: auto
focalcomp:
  enable: 0
  focalICAout: auto
autocorr:
  enable: 0
  autocorrint: 20
  dropautocorr: auto
opts:
  noplot: 0
  nocompute: 0
  FontSize: 14
Index exceeds the number of array elements (1).

Error in pop_selectcomps (line 168)
    set( button, 'backgroundcolor', eval(fastif(EEG.reject.gcompreject(ri), COLREJ,COLACC)), 'string', int2str(ri));

Error in eeg_SASICA (line 93)
        eval(cfg);

Error in eeg_SASICA (line 742)
            eeg_SASICA(EEG,['pop_selectcomps(EEG, [' num2str(cmps) '],' num2str(ncomp) ');']);

Error in SASICA>push_ok_Callback (line 601)
    [EEG, cfg] = eeg_SASICA(EEG,cfg);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in SASICA (line 110)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)SASICA('push_ok_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by lucapton** [comment]
This is not the right forum for this question. As the error suggests, you could send an email to max.chaumon@gmail.com. Alternatively you could ask for help on the [EEGLAB listserv](https://sccn.ucsd.edu/wiki/EEGLAB_mailing_lists).
