### ISSUE TITLE
Python Implementation

### ISSUE THREAD

**Issue by yjmantilla** [sccn/ICLabel#14]
I'm planning to do a python implementation of IClabel , mainly for use in MNE-python. I couldn't see any file referencing the license information. I was wondering if there was a problem with me doing the translation and releasing it; obviously mentioning that it is a mere translation of this project.

Thanks you for your time.

**Comment by lucapton** [comment]
I don't have any problem with that so long as it references back to this project and to the publication. I suggest you take a look at [this repository](https://github.com/lucapton/ICLabel-Train). I'm don't know if you're aware, but the ICLabel classifier was originally trained in python using tensorflow. This project is a reimplementation in matlab that just import the weights. If you decide to move forward with this, we should speak further as I can share some of those files and likely make your life a lot easier.

**Comment by yjmantilla** [comment]
Thanks for your response! I was aware it was originally trained in python. I'm not the most experienced with tensorflow but I look forward to learn more with this project. 

Currently I'm helping in an implementation of the PREP pipeline in python (https://github.com/sappelhoff/pyprep) . I will try to mimic the style of that project as far as I can.  I'm planning to start the translation before the end of February as I'm flushing out some other code projects right now.

If you can please see the pyprep repository I mentioned earlier. Would like to see if you agree with that approach. The files you mention will surely be helpful.

**Comment by lucapton** [comment]
pyprep seems good from the quick look I took. The only comment I have is that copying the raw dataset seems unecessary if you never actually change it. You could just point to it to save memory.

Let me know if you decide you need anything.

**Comment by yjmantilla** [comment]
Thanks! I will have to check if indeed it is never modified. Since the code was done by many people is hard to keep track of everything so we are in the task of creating tests to make sure that the code is not broken suddenly by a pull request.

I will inform you when I start this project  (expected: beginning of March). Until then !

**Comment by yjmantilla** [comment]
Ok I have started exploring this a little bit yesterday. Currently very busy but I hope that with constant effort this will be at some point be done.

What follows are my conclusions of this first dive 
### **(you may skip to the Question part if you wish)**:

As of now with my initial exploration I now see that making the features in a similar way to matlab is not trivial. Currently I'm looking at the topoplotFast.m script.

# The problems:
- In mne i only have access to cartesian coordinates. Looking at readlocs.m and converlocs.m I was able to get the same Th variable but not the same Rd one... My guess is that in the file I was testing the radius was not inferred from the cartesian coordinates but Im not sure.
- The griddatav4 interpolation has no translation in python. I tried to do a local translation and also tested an interpolation based on a radial function (Rbf) taking inspiration on these discussions [1 ](https://scipy-dev.scipy.narkive.com/gpiUk8VE/griddata-equivalent-of-matlab-v4-option) and [2](https://github.com/mne-tools/mne-python/issues/1308).

# Comparison
When comparing the translation to the original iclabel at [this](https://github.com/sccn/ICLabel/blob/e5ceed0c8a7661456581a201242b53198d67e3b6/topoplotFast.m#L960) line of topoplotFast.m (first component)
``` 
[Xi,Yi,Zi] = griddata(double(inty),double(intx),double(intValues),double(yi)',double(xi),'v4'); % interpolate data
``` 
I get these heatmaps of Zi:

- Matlab
![matlab](https://user-images.githubusercontent.com/36543115/108429667-4b197400-720e-11eb-8718-f5fdb29ad08f.png)

- Rbf (Note different scale which may be because Rd is different?)
![rbf](https://user-images.githubusercontent.com/36543115/108429799-700de700-720e-11eb-82ff-c82793e5300e.png)

- My translation of griddatav4 (huge fail but the scale seems somewhat better):

![my1](https://user-images.githubusercontent.com/36543115/108429918-9af83b00-720e-11eb-8d2c-5901ae11eeec.png)

I got a bit deeper and maybe the problem is the builtin function _mergesimpts which I tried to translate vaguely (since there is no source code).  EDIT: NO, the Rd problem had a heavy influence, once solved the match between matlab and python was much better.

By inputting the result of mergepoints2D(x,y,v) of matlab into my gdatav4 function I get better results so the problem may as well be there in _mergesimpoints (along with the different Rd 😢   )

![my2](https://user-images.githubusercontent.com/36543115/108430289-24a80880-720f-11eb-969b-8ca68f3042d7.png)


I think the Rd problem may not be easily solvable but maybe I can replicate _mergesimpts better.

EDIT: BOth problems solved.


# Question:

I guess the python translation will be able to have the same image in terms of relative values but getting the same exact ones may be too hard.

- How sensitive do you think classifier will be to changes in the absolute values of the 32x32 image ? 

PD: I foresee problems when getting into the ECD model fit through dipfit. I have not yet looked for python equivalents though hopefully MNE will have some similar enough.

**Comment by lucapton** [comment]
It's hard to answer that question, but potentially quite sensitive. This is the downside to using neural networks. It's mostly a mystery.

ICLabel does not use dipole fits so that's not an issue.

**Comment by datalw** [comment]
I just want to say, @yjmantilla it is a very good idea to implement in python : )
Since we are using python in our project of EEG pattern recognition, and we REALLY need a well-functioning automated artefact removal tool. Looking forward to the integration in MNE!!!

**Comment by yjmantilla** [comment]
> I just want to say, @yjmantilla it is a very good idea to implement in python : )
> Since we are using python in our project of EEG pattern recognition, and we REALLY need a well-functioning automated artefact removal tool. Looking forward to the integration in MNE!!!

Thanks @datalw! If there is anyone willing to help that would be awesome. MNE would benefit a lot from having this classification tool, sadly I have been very busy with university and work but I hope I will be able to work on this little by little.

**Comment by lucapton** [comment]
@yjmantilla Is your version of MATLAB's v4 interpolation available somewhere? I didn't see it in your iclabelpy repo. Relatedly, is it based on [the original biharmonic spline interpolation paper](https://pdfs.semanticscholar.org/9a16/324b37c9a6ed0a5dcff30761c96979cbc14c.pdf?_ga=2.136122101.598148328.1616127484-1508922795.1616127484)?

**Comment by yjmantilla** [comment]
@lucapton  What i did was a really crude translation of gdatav4 that is *supposedly* based on that paper. Im not really math-versed so I dont claim to understand the code nor the paper 😬 .

Here is the code:

https://github.com/yjmantilla/iclabelpy/blob/3a677ebc4aa47351fd2d742f5ff8127f7602cf29/iclabelpy/utils.py#L136

The problem really is the first line of gdatav4 in matlab:

```[x, y, v] = mergepoints2D(x,y,v);```

I cannot replicate this first line since it depends on:

``` 
xyv = builtin('_mergesimpts', [y, x, real(v), imag(v)],[myepsy, myepsx, Inf, Inf], 'average');
```

Which is a builtin function that i have not yet reverse engineered.

To be sure the function I translated works correctly at least after that "mergepoints2D" line I inputted the result of merge2points from matlab into my gdatav4 translation. The plot seems to follow the same one I plotted in matlab but I have not verified that the values are exactly the same yet.


Now, theoretically, I guess the ideal implementation of the method described in the paper shouldnt depend so closely on a builtin function from matlab, so maybe there is a workaround.


Recently I found another version of gdatav4 that doesnt rely on the builtin function but I have not yet tried it:
https://github.com/dmgroppe/Mass_Univariate_ERP_Toolbox/blob/d1e60d42c5f42eabaeb35d28c99050ddf62fb89d/griddata2.m#L252

Maybe in the past that mergesimpts built-in function didn't exist in matlab and there was another implementation that I could try if i found it. I suspect this because I keep finding gdatav4 codes with some variations:
http://kutaslab.ucsd.edu/matlabmk_fn_docs/matlabmk/griddata2.html
http://blog.sina.com.cn/s/blog_5da928d70101g7py.html

PD: Here is a link to a copy of griddata.m if you dont feel like looking for the real file in matlab https://www.jianshu.com/p/fca3191c314e

**Comment by datalw** [comment]
> 
> 
> > I just want to say, @yjmantilla it is a very good idea to implement in python : )
> > Since we are using python in our project of EEG pattern recognition, and we REALLY need a well-functioning automated artefact removal tool. Looking forward to the integration in MNE!!!
> 
> Thanks @datalw! If there is anyone willing to help that would be awesome. MNE would benefit a lot from having this classification tool, sadly I have been very busy with university and work but I hope I will be able to work on this little by little.

I have been thinking to do some contribution to MNE myself in my free time, since I am using it for my work nearly on a daily base. Currently I am trying to find time to study the "Contributing guide" of mne. Hopefully I can make some quick progress on it : D

**Comment by lucapton** [comment]
@yjmantilla That's a great start! I'm not sure if you're aware, but that last site that you linked has an implementation of `mergepoints2d` in it (if it can be trusted) starting on line 139. Copied below:

```matlab

function [x, y, v] = mergepoints2D(x,y,v)

% Sort x and y so duplicate points can be averaged

%Need x,y and z to be column vectors
sz = numel(x);
x = reshape(x,sz,1);
y = reshape(y,sz,1);
v = reshape(v,sz,1);
myepsx = eps(0.5 * (max(x) - min(x)))^(1/3);
myepsy = eps(0.5 * (max(y) - min(y)))^(1/3);


% look for x, y points that are indentical (within a tolerance)
% average out the values for these points
if isreal(v)
    xyv = builtin('_mergesimpts', [y, x, v], [myepsy, myepsx, Inf], 'average');
    x = xyv(:,2);
    y = xyv(:,1);
    v = xyv(:,3);
else
    % if z is imaginary split out the real and imaginary parts
    xyv = builtin('_mergesimpts', [y, x, real(v), imag(v)], ...
        [myepsy, myepsx, Inf, Inf], 'average');
    x = xyv(:,2);
    y = xyv(:,1);
    % re-combine the real and imaginary parts
    v = xyv(:,3) + 1i*xyv(:,4);
end
% give a warning if some of the points were duplicates (and averaged out)
if sz>numel(x)
    warning(message('MATLAB:griddata:DuplicateDataPoints'));
end
```

**Comment by yjmantilla** [comment]
@lucapton  Sorry for the late reply. Indeed I translated that one . The problem was precisely the following line:

```matlab
xyv = builtin('_mergesimpts', [y, x, v], [myepsy, myepsx, Inf], 'average');
```

Because it depended on a built-in function that has no code. So i had to reverse-engineer it. I think i may have done it. I did some tests and the results of that built-in function agrees with the matlab results.

I have yet to do a test for the whole gdatav4 function but I think that now that the built-in function has been taken care of this will be more easier.

EDIT: Here is a single test I did

![image](https://user-images.githubusercontent.com/36543115/116847492-43802f00-abb0-11eb-8db4-20dade0b8dc3.png)


I put these results on a separate module because i think that interpolation code may be of interest beyond iclabel.

Here is the repository:
https://github.com/yjmantilla/gdatav4

**Comment by yjmantilla** [comment]
Ok, another update in case this is useful for anyone. This is related to the Rd problem I mentioned here:

>In mne i only have access to cartesian coordinates. Looking at readlocs.m and converlocs.m I was able to get the same Th variable but not the same Rd one... My guess is that in the file I was testing the radius was not inferred from the cartesian coordinates but Im not sure.

In mne locations are saved in cartesian coordinates. The objective is to convert the coordinates to spherical and then to "polar coordinates for a topoplot (not cylindrical)".

The procedure is simple:

```python
locs = raw._get_channel_positions()

#%% Obtain carthesian coordinates
X = locs[:,1]
Y = -1*locs[:,0] # be mindful of the nose orientation in eeglab and mne 
# see https://github.com/mne-tools/mne-python/blob/24377ad3200b6099ed47576e9cf8b27578d571ef/mne/io/eeglab/eeglab.py#L105
Z = locs[:,2]

#%% Obtain Spherical Coordinates 
sph = np.array([cart2sph(X[i],Y[i],Z[i]) for i in range(len(X))])
theta = sph[:,0]
phi = sph[:,1]

#%% Obtain Polar coordinates (as in eeglab)
topo = np.array([sph2topo(theta[i],phi[i]) for i in range(len(theta))])
Rd = topo[:,1]
Th = topo[:,0]
```
Now, the individual conversion codes:

For carthesian to spherical is the standard stuff

```python
def cart2sph(x,y,z):
    azimuth = np.arctan2(y,x)
    elevation = np.arctan2(z,np.sqrt(x**2 + y**2))
    r = np.sqrt(x**2 + y**2 + z**2)
    # theta,phi,r
    return azimuth, elevation, r
```

NOTE: Im working in radians in python

Now, for spherical to polar (not cylindrical) you will find this sph2topo() function in eeglab, which is basically:

```matlab
  angle  = -horiz;
  radius = 0.5 - az/180;
```

So, dont translate this directly. Being more mindful these formulas seem to be normalized by pi.  That is the real formula is np.pi/2 - az (in radians).


So the correct code in python is:

```python
def sph2topo(theta,phi):
    az = phi
    horiz = theta
    angle  = -1*horiz
    radius = (np.pi/2 - az)/np.pi
    return angle,radius
```

This way I could finally get the same Rd as matlab.

**Comment by yjmantilla** [comment]
More updates.

I have managed to reproduce the topoplot and psd features at least for a test case. The psd is problematic since it depends on a random number generator that I wasn't able to match exactly inside numpy. So for the test I had to input the random sequence from matlab. I hope the feature results don't depend too much on these random numbers...

As of now I'm trying to implement the autocorr feature extraction. After that is done (EDIT: I've got a rough implementation of the eeg_autocorr_fftw branch) I guess the approach would be to:
- Implement the neural net
- Compare the probabilities results of the test case from matlab and python


If it is a good enough match maybe it is possible after all to use the already trained neural net in python

**Comment by yjmantilla** [comment]
@lucapton  Do you have a backup of the already trained model in tensorflow? Would be helpful. I'm trying to compare the results of iclabel and the translation I did.

As of now Im trying to train a model with the repositories you mentioned.

Another possibility is to use [pytorch-mcn](https://github.com/albanie/pytorch-mcn) to import a MatConvNet model, but it is kind of like doing too many steps seeing that the model was originally in python and another problem is that the project seems staled.

**Comment by yjmantilla** [comment]
So I did a test to see what would happen if I entered the python inferred features inside matlab iclabel for a test file.

Here are the results:

| matlab label | python label | matlab prob | python prob |
|--------------|--------------|-------------|-------------|
| 3            | 3            | 0.76810551  | 0.945873    |
| 3            | 3            | 0.90020537  | 0.958792    |
| 2            | 1            | 0.5031628   | 0.742126    |
| 1            | 1            | 0.5364629   | 0.967997    |
| 1            | 1            | 0.45677382  | 0.770459    |
| 1            | 1            | 0.49330348  | 0.837219    |
| 1            | 1            | 0.5959028   | 0.96672     |
| 3            | 3            | 0.69566238  | 0.733691    |
| 1            | 1            | 0.92298758  | 0.993569    |
| 1            | 1            | 0.34082744  | 0.977488    |
| 1            | 1            | 0.4926008   | 0.778822    |
| 7            | 1            | 0.52634716  | 0.910113    |
| 1            | 1            | 0.84622681  | 0.970226    |
| 1            | 1            | 0.52686352  | 0.850633    |
| 1            | 1            | 0.9757508   | 0.989004    |
| 1            | 1            | 0.73601401  | 0.949292    |
| 1            | 1            | 0.94925791  | 0.997398    |
| 1            | 1            | 0.98313206  | 0.982973    |
| 7            | 1            | 0.55026978  | 0.631363    |
| 1            | 1            | 0.81073719  | 0.919597    |
| 1            | 1            | 0.75044942  | 0.949451    |
| 2            | 1            | 0.62744248  | 0.704255    |
| 1            | 1            | 0.97050011  | 0.97988     |
| 1            | 1            | 0.94245189  | 0.978117    |
| 1            | 1            | 0.96294612  | 0.95458     |
| 1            | 1            | 0.79089719  | 0.6366      |
| 1            | 1            | 0.64256382  | 0.491642    |
| 1            | 1            | 0.99037588  | 0.977877    |
| 1            | 1            | 0.98314077  | 0.96794     |
| 1            | 1            | 0.59098762  | 0.521587    |
| 1            | 1            | 0.671565    | 0.633237    |
| 1            | 1            | 0.96913141  | 0.964465    |
| 7            | 7            | 0.69773477  | 0.839805    |
| 1            | 1            | 0.89494622  | 0.900599    |
| 2            | 2            | 0.73963076  | 0.851301    |
| 7            | 7            | 0.56897843  | 0.409293    |
| 7            | 7            | 0.87383592  | 0.926843    |
| 1            | 1            | 0.91448039  | 0.884928    |
| 1            | 1            | 0.85773915  | 0.823048    |
| 1            | 1            | 0.66675586  | 0.586207    |
| 7            | 7            | 0.76000512  | 0.881198    |
| 1            | 7            | 0.43611225  | 0.446263    |
| 7            | 7            | 0.50264001  | 0.63922     |
| 1            | 1            | 0.70572883  | 0.739486    |
| 7            | 7            | 0.53324783  | 0.543668    |
| 7            | 7            | 0.41765407  | 0.391823    |
| 7            | 7            | 0.92149413  | 0.952384    |
| 7            | 7            | 0.52833509  | 0.662627    |
| 1            | 1            | 0.85205013  | 0.900016    |
| 7            | 6            | 0.55265778  | 0.514466    |
| 7            | 7            | 0.5318709   | 0.757319    |
| 2            | 2            | 0.38847792  | 0.330268    |
| 2            | 2            | 0.66525137  | 0.319512    |

number of different labels = 6 / 53
MSE = 0.035127264


There are two places where I know different results arise despite the best of my efforts:
- Surprisingly a matrix multiplication (icaact = demixing @ eeg), gives different results inside matlab and python even if I load the exact same data. This may be because matlab and python use different a different BLAS version (?).
- Producing the random subset for the eeg_rpsd function, I couldn't replicate the same permutation.

So, what happens if both of this errors are corrected (artificially put the matlab data inside python at the appropriate places) :

| matlab label | python label | matlab prob | python prob |
|--------------|--------------|-------------|-------------|
| 3            | 3            | 0.76810551  | 0.785883    |
| 3            | 3            | 0.90020537  | 0.684227    |
| 2            | 1            | 0.5031628   | 0.49069     |
| 1            | 1            | 0.5364629   | 0.513763    |
| 1            | 1            | 0.45677382  | 0.504196    |
| 1            | 1            | 0.49330348  | 0.883677    |
| 1            | 1            | 0.5959028   | 0.766535    |
| 3            | 3            | 0.69566238  | 0.818233    |
| 1            | 1            | 0.92298758  | 0.990033    |
| 1            | 1            | 0.34082744  | 0.973997    |
| 1            | 1            | 0.4926008   | 0.716925    |
| 7            | 1            | 0.52634716  | 0.60772     |
| 1            | 1            | 0.84622681  | 0.78287     |
| 1            | 1            | 0.52686352  | 0.663432    |
| 1            | 1            | 0.9757508   | 0.565682    |
| 1            | 1            | 0.73601401  | 0.909971    |
| 1            | 1            | 0.94925791  | 0.981488    |
| 1            | 1            | 0.98313206  | 0.97932     |
| 7            | 1            | 0.55026978  | 0.362695    |
| 1            | 1            | 0.81073719  | 0.836489    |
| 1            | 1            | 0.75044942  | 0.67658     |
| 2            | 1            | 0.62744248  | 0.699901    |
| 1            | 1            | 0.97050011  | 0.91058     |
| 1            | 1            | 0.94245189  | 0.984178    |
| 1            | 1            | 0.96294612  | 0.971967    |
| 1            | 1            | 0.79089719  | 0.65719     |
| 1            | 1            | 0.64256382  | 0.545296    |
| 1            | 1            | 0.99037588  | 0.995731    |
| 1            | 1            | 0.98314077  | 0.978435    |
| 1            | 1            | 0.59098762  | 0.520621    |
| 1            | 1            | 0.671565    | 0.63149     |
| 1            | 1            | 0.96913141  | 0.967077    |
| 7            | 7            | 0.69773477  | 0.783285    |
| 1            | 1            | 0.89494622  | 0.889788    |
| 2            | 2            | 0.73963076  | 0.82125     |
| 7            | 7            | 0.56897843  | 0.552044    |
| 7            | 7            | 0.87383592  | 0.918926    |
| 1            | 1            | 0.91448039  | 0.921539    |
| 1            | 1            | 0.85773915  | 0.827151    |
| 1            | 1            | 0.66675586  | 0.658635    |
| 7            | 7            | 0.76000512  | 0.880322    |
| 1            | 7            | 0.43611225  | 0.470414    |
| 7            | 7            | 0.50264001  | 0.558221    |
| 1            | 1            | 0.70572883  | 0.655859    |
| 7            | 7            | 0.53324783  | 0.51245     |
| 7            | 1            | 0.41765407  | 0.61678     |
| 7            | 7            | 0.92149413  | 0.926445    |
| 7            | 7            | 0.52833509  | 0.658561    |
| 1            | 1            | 0.85205013  | 0.925306    |
| 7            | 6            | 0.55265778  | 0.479987    |
| 7            | 7            | 0.5318709   | 0.736651    |
| 2            | 2            | 0.38847792  | 0.362704    |
| 2            | 2            | 0.66525137  | 0.312291    |

number of different labels = 7 / 53
MSE = 0.024345493

- Surprisingly now there are more different labels but the MSE diminished.

**Comment by lucapton** [comment]
Great progress! I hope I don't miss anything:

- The random number generator difference _shouldn't_ matter so long as your generating numbers from the same distribution. I don't think you'd want to set the random seed or anything like that.

- I looked through the old folders and was able to find a single model that was still saved in tensorflow format. Everything else is mat files. I can share it but it's a tad large at nearly a GB. Compressed, it's down to 760 MB. I've included test files which provide know input/intermediate/output values for testing.  Let me know how best to send it to you.

- I don't understand why the results would be different if you copied over the features. Is it a retrained network rather than a copy?

**Comment by yjmantilla** [comment]
Hi @lucapton , sorry for the incredibly late reply (got into google summer of code and been mostly working on that).

>I looked through the old folders and was able to find a single model that was still saved in tensorflow format. Everything else is mat files. I can share it but it's a tad large at nearly a GB. Compressed, it's down to 760 MB. I've included test files which provide know input/intermediate/output values for testing. Let me know how best to send it to you.

Whatever works best for you. I would upload to a google drive and share it, but you could use [wetransfer](https://wetransfer.com/)

>I don't understand why the results would be different if you copied over the features. Is it a retrained network rather than a copy?

Nope, is the same network. The difference are that the features aren't the exact same.

The first test (number of different labels = 6 / 53, MSE = 0.035127264) was:

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBlZWdbXCJlZWcgIGRlbWl4aW5nXCJdLS0-fFwiaWNhYWN0PWRlbWl4aW5nQGVlZ1wifHB5dGhvbl9mZWF0dXJlX2V4dHJhY3Rvci0tPnJ1bl9JQ0xcbiAgICBlZWctLT5pY2xhYmVsX2ZlYXR1cmVfZXh0cmFjdG9yLS0-cnVuX0lDTFxuICAgIHJ1bl9JQ0wtLT5weXRob25fbGFiZWxzLS0-Y29tcGFyZVxuICAgIHJ1bl9JQ0wtLT5tYXRsYWJfbGFiZWxzLS0-Y29tcGFyZVxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImZvcmVzdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/edit/##eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBlZWdbXCJlZWcgIGRlbWl4aW5nXCJdLS0-fGljYWFjdD1kZW1peGluZ3xweXRob25fZmVhdHVyZV9leHRyYWN0b3ItLT5ydW5fSUNMXG4gICAgZWVnLS0-aWNsYWJlbF9mZWF0dXJlX2V4dHJhY3Rvci0tPnJ1bl9JQ0xcbiAgICBydW5fSUNMLS0-cHl0aG9uX2xhYmVscy0tPmNvbXBhcmVcbiAgICBydW5fSUNMLS0-bWF0bGFiX2xhYmVscy0tPmNvbXBhcmVcbiIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJmb3Jlc3RcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)

The second test (number of different labels = 7 / 53, MSE = 0.024345493) was:

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBlZWdbXCJpY2FhY3QgYW5kIHNhbWUgcmFuZG9tIHN1YnNldCBpbiBlZWdfcnBzZCBmdW5jdGlvblwiXS0tPnxcImljYWFjdCBmcm9tIGlucHV0XCJ8cHl0aG9uX2ZlYXR1cmVfZXh0cmFjdG9yLS0-cnVuX0lDTFxuICAgIGVlZy0tPmljbGFiZWxfZmVhdHVyZV9leHRyYWN0b3ItLT5ydW5fSUNMXG4gICAgcnVuX0lDTC0tPnB5dGhvbl9sYWJlbHMtLT5jb21wYXJlXG4gICAgcnVuX0lDTC0tPm1hdGxhYl9sYWJlbHMtLT5jb21wYXJlXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZm9yZXN0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/edit/##eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBlZWdbXCJpY2FhY3QgYW5kIHNhbWUgcmFuZG9tc3Vic2V0IGluIGVlZ19ycHNkIGZ1bmN0aW9uXCJdLS0-fFwiaWNhYWN0IGZyb20gaW5wdXRcInxweXRob25fZmVhdHVyZV9leHRyYWN0b3ItLT5ydW5fSUNMXG4gICAgZWVnLS0-aWNsYWJlbF9mZWF0dXJlX2V4dHJhY3Rvci0tPnJ1bl9JQ0xcbiAgICBydW5fSUNMLS0-cHl0aG9uX2xhYmVscy0tPmNvbXBhcmVcbiAgICBydW5fSUNMLS0-bWF0bGFiX2xhYmVscy0tPmNvbXBhcmVcbiIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJmb3Jlc3RcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)

Before I said:

>Surprisingly a matrix multiplication (icaact = demixing @ eeg), gives different results inside matlab and python even if I load the exact same data. This may be because matlab and python use different a different BLAS version (?).

I think this problem is not the multiplication, is just that the data is not exactly the same (it is pretty pretty close though, just not exactly the same).

For example in the demixing matrix one value will be -1302100.041765983 in python when in matlab is -1302100.03896358 (on an arbitrary item)

I think that the differences end up accumulating and  the ica activation will for example have 3.566399 in python and -4.4336009 in matlab (on an arbitrary item).

**Comment by adam2392** [comment]
@yjmantilla or @lucapton do either of you have a link to the trained tensorflow model. @jacobf18 and the team here have gotten to replicate the feature 4D array generation step. And now interested in validating that the fed in Python features into the equivalent Python CNN model will result in similar performance as if it was done through EEGLab.

Would either of you be able to share a dropbox link or something to the tensor flow model that we can download?

**Comment by yjmantilla** [comment]
Hi @adam2392 , unfortunately I dont have it as I never had the time (nor the computer hehe) to train it. Hopefully lucapton has it. 

Im really happy to see that you were able to replicate the feature generation steps.

**Comment by datalw** [comment]
> 
> 
> @yjmantilla or @lucapton do either of you have a link to the trained tensorflow model. @jacobf18 and the team here have gotten to replicate the feature 4D array generation step. And now interested in validating that the fed in Python features into the equivalent Python CNN model will result in similar performance as if it was done through EEGLab.
> 
> Would either of you be able to share a dropbox link or something to the tensor flow model that we can download?

I also would like to have the trained tensorflow model to import into python to do some testing, comparison or so, if it is possible to be downloaded.

**Comment by lucapton** [comment]
Okay it took me a long time to track it down but I think i have [the files for the python version of ICLabel](https://www.dropbox.com/sh/mnda912bnrwv4q2/AAD32Lup4880tDzakWKqpak9a?dl=0)!

In there you should find two folders: one with "autocorr" in the name which is ICLabel and the one without which is ICLabelLite. In each of those folders there are two mat files, one containing the weights of the model and the other containing inputs and activation values at each layer (for checking correct model implementation). There are also two sub folders which contain the frozen tensorflow models. I don't know if those are going to be usable as the models were saved a long time ago with tensorflow 1.4.0.  The original model code can be found [here](https://github.com/lucapton/ICLabel-Train) in `tfMLP.py`.

Give it a shot and let me know how it goes.

**Comment by mscheltienne** [comment]
What is the status of this project?
@yjmantilla It looks like you discontinued this project in favor of @jacobf18 @adam2392 implementation: https://github.com/jacobf18/iclabel-python

I'm working at 20% for the M/EEG platform at FCBG (Geneva), and we intend to work on ICLabel python implementation and integration with MNE. Any previous work to build upon or to contribute to will speed up development and improve quality.

**Comment by adam2392** [comment]
@mscheltienne currently, @jacobf18 has done some validation to port the feature-generation step from the ICA time series from Matlab -> Python. I refactored the code to have a MNE-style API, and eventually I think it would be awesome to have this sit in the mne.tools repository as perhaps `mne-iclabel`, or something like that.

In terms of details, Jacob can speak more to it than I. He is currently attempting to replicate the original network in modern pytorch. The main bottleneck is that the network was written in an outdated tensor flow version, and porting over is non-trivial. The original implementation will serve as a benchmark. 

Once he has done that, our intention is actually to take the network and improve it possibly by using a new network, or providing different classification models (i.e. forests) and open-sourcing the model in `mne-iclabel`. This will be done mainly via a new dataset provided by @agramfort . We use a new dataset primarily because there are some limitations currently to port over ICLabel.

the original raw data is not accessible, so if we change anything about the input data, automatically, the IClabel architecture is unusable. Our hypothesis is that we can improve the performance by perhaps doing end-to-end training from the raw ICA time series themselves.

Happy to collaborate and work together on this. @jacobf18 is the main lead on this project. Wdyt?

**Comment by mscheltienne** [comment]
Thanks for the reply, I see a lot of groundwork has already been done. At FCBG, we have the same vision: propose both the current network and an improvement upon it to our researchers, in python and compatible with MNE.
Somewhere at the beginning of 2022, we also have a ML master student who can work full time on this project for 6 months, and we would be happy to collaborate.

**Comment by adam2392** [comment]
Sounds good! perhaps it might be good to schedule a short call once your student is onboard, and we can see what tasks remain till we get a useful tool out of this?

**Comment by yjmantilla** [comment]
@mscheltienne correct, I discontinued the project and linked that old repo to jacob's one. I think at least the gdatav4 translation was useful 😬

**Comment by mscheltienne** [comment]
@adam2392 @jacobf18 Would you be available for a short call to discuss this? 
At FCBG, the ML student will start on March 1st, but it would be nice if we could already have a quick chat before that. 
You can contact me with your availability at mathieu.scheltienne@fcbg.ch

**Comment by adam2392** [comment]
Just FYI: https://github.com/adam2392/mne-icalabel contains the full port.

The repo is soon-to-be migrated to https://github.com/mne-tools/mne-icalabel

**Comment by lucapton** [comment]
Congratulations! This is really impressive! I see you were even able to replicate topoplot. Well done. Do you know how closely it replicates results from the EEGLAB plugin?

**Comment by mscheltienne** [comment]
It should be an exact replication. 

See this test for the network run on a set of features: https://github.com/adam2392/mne-icalabel/blob/0c4cf0ad749f13497f1abb5c3ec9a577388de11c/mne_icalabel/iclabel/tests/test_network.py#L174-L187
And this test for the feature extraction: https://github.com/adam2392/mne-icalabel/blob/0c4cf0ad749f13497f1abb5c3ec9a577388de11c/mne_icalabel/iclabel/tests/test_features.py#L114-L149

**Comment by lucapton** [comment]
Congratulations on the paper to everyone involved! I just saw the notification this morning.
