### ISSUE TITLE
Problems with ICLabel-Dataset - download link is not working

### ISSUE THREAD

**Issue by ledovsky** [sccn/ICLabel#18]
Hi @lucapton!
Thanks for the project and sharing the code!
My colleagues and I are building our own dataset for IC classification and also developing ML model

I tried to download ICLabel dataset for exploration using https://github.com/lucapton/ICLabel-Dataset but the link is not working. The corresponding issue in ICLabel-Dataset repo is not answered so I decided to ask here!

Is there a way to download the dataset?

Thx a lot!

**Comment by lucapton** [comment]
I've answered the original issue so lets talk there. Thanks for the reminder.
