### ISSUE TITLE
Change ms to sec in Scrolling Component Activity

### ISSUE THREAD

**Issue by RodriigoGM** [sccn/ICLabel#20]
I'm analysing many EEG dataset with 3000-4000 sec per dataset, so I'll prefer to watch de scrolling activity in second (not in milisecond, as is default configuration). I tried edit %number of pint to draw in scrollplot.m line 61... but it didn't works (I'm really new programing). May someone explain to me how to do it? please.

I'm using Matlab R2020b and EEGLAB 2021.

Best wishes,

RodrigoGM

**Comment by lucapton** [comment]
I think you'll want to change line 188 to 
```matlab
xticklabel = times(s1) / 1000;
```
and line 193 to 
```matlab
xticklabel = times(xtick) / 1000;
```

I haven't tested it so there may be other such changes to make, but they should all be along those lines (converting milliseconds to seconds).

**Comment by RodriigoGM** [comment]
Thank you very much. It function perfect!
I also changed in "prp_prop_extended.m" the line 215 'Time (ms)' to 'Time (s)'.
