### ISSUE TITLE
Classify components using ICLabel problem

### ISSUE THREAD

**Issue by tingyu653** [sccn/ICLabel#21]
I run ICA, and after ICA I use classify components using ICLabel.
It works well until the 9th data.(to the tenth)I got this problem. How can I solve it?
![image](https://user-images.githubusercontent.com/85797007/122542973-de986f80-d05d-11eb-9ae8-a83cfad3ecc4.png)

**Comment by lucapton** [comment]
This indicated a problem in your ICA decomposition. Imaginary components in the ICA solution can happen if your data are single-precision. If that's the case, try converting EEG.data to double-precision and then rerun your ICA algorithm of choice and try again.
