### ISSUE TITLE
ICLabel not showing on tools after installation.

### ISSUE THREAD

**Issue by sharjeelkhann** [sccn/ICLabel#22]
![image](https://user-images.githubusercontent.com/52481789/124882598-ff633d80-dfe9-11eb-9b68-f62e7b4d4e29.png)
[](url)
![image](https://user-images.githubusercontent.com/52481789/124882826-320d3600-dfea-11eb-80d9-194c19fad1de.png)
I have installed IClabel plugin but it's not showing in tools.

**Comment by lucapton** [comment]
It's the fourth option below the one you had highlighted ("Run ICA") which says "Classify components using ICLabel"
