### ISSUE TITLE
Threshold for deleting eye-components

### ISSUE THREAD

**Issue by DouweHorsthuis** [sccn/ICLabel#24]
We have been using your amazing tool for a while now in our lab and whenever we are talking about it in a lab meeting, some people argue that if they would manually only delete eye components, they would sometimes delete different ones as well. It's pretty clear to me that this has to do with the threshold we use to delete components once they are flagged. In my case when I am deleting eye components only I am using the following 2 lines to decide what is bad and what is not: 

ICA_components = EEG.etc.ic_classification.ICLabel.classifications ; 
bad_components = find(ICA_components(:,3)>0.80 & ICA_components(:,1)<0.05); 

This made me wonder, is there some sort of threshold you would suggest? I can't seem to find this in the paper or in the readme of this Repo

Thank you so much for your time

**Comment by lucapton** [comment]
Yes, if you check the accompanying paper there is a table which suggests per-class thresholds.
