### ISSUE TITLE
Methods from original paper (replicability study)

### ISSUE THREAD

**Issue by sunshineinsandiego** [sccn/ICLabel#25]
Hi - Hoping someone could answer some questions about the ICLabel data processing / feature extraction methods that were used to construct the data set.  I couldn't find the details in the original paper: https://doi.org/10.1016/j.neuroimage.2019.05.026. 

- Are the original EEGs average referenced?
- How are the original EEGs pre-processed prior to applying ICA? PCA/standardized? 
- Which ICA algorithm was applied to generate the ICs?
- From the code it looks like the EEG data was average referenced prior to applying ICA?
- It seems like the original EEG recordings as well as the ICs are of varying lengths / sampling frequencies?

Also, in this paper (https://sccn.ucsd.edu/~scott/pdf/ICLabel19.pdf), the ICLabel dataset is supposedly available. It notes that "Prior to computing features, each dataset was converted to a common average reference." Assuming here that this means the raw EEG?

Will likely have more questions about the PSD/Autocorr feature extraction when I get there. Thanks for any thoughts!

**Comment by lucapton** [comment]
Let me preface this by explaining that we did not record any data specifically for ICLabel. The ICLabel dataset is an aggregation of datasets that were recorded, processed, and analyzed in numerous ways by numerous people, both local to the SCCN and visiting from elsewhere.

- Are the original EEGs average referenced?
  - It varies by dataset
- How are the original EEGs pre-processed prior to applying ICA? PCA/standardized?
  - It varies by dataset
- Which ICA algorithm was applied to generate the ICs?
  - It varies by dataset, but mostly infomax ICA (runica and amica are likely the two most common)
- From the code it looks like the EEG data was average referenced prior to applying ICA?
  -  It varies by dataset whether or not datasets were average referenced or not be ICA, but I did make sure everything was average referenced before extraction features.
- It seems like the original EEG recordings as well as the ICs are of varying lengths / sampling frequencies?
  - Correct.

Hope that helps.
