### ISSUE TITLE
Some errors always occur when running iclabel

### ISSUE THREAD

**Issue by Lee666666** [sccn/ICLabel#26]
My computer OS is Win10, and matlab version 2019b. Recently, errors are always reported when using IClabel plug-in.  The error is EEGLAB error in function run_ICL() at line 30:  Unable to parse the name: dagnn_be.DagNN.loadobj. I want to know how to solve this problem. Thank you!
![微信图片_20211009190627](https://user-images.githubusercontent.com/74190074/136655527-92c1c19c-fa32-40a7-98d0-070507cb2726.png)

**Comment by wmmzju** [comment]
Hi, I have the same problem, do you remember how you solved it?
