### ISSUE TITLE
Check if data is referenced to CAR

### ISSUE THREAD

**Issue by mscheltienne** [sccn/ICLabel#28]
After some digging following: https://github.com/sccn/eeglab/issues/462
This [line ](https://github.com/sccn/ICLabel/blob/e8abc99e0c371ff49eff115cf7955fafc7f7969a/ICL_feature_extractor.m#L15) checks if the dataset is referenced to a common average. But, the sample EEGLAB dataset field `.ref` is set to `common`, which is probably a CAR? And yet this is not captured by `~strcmp(EEG.ref, 'averef')`. 

Same for a dataset outputted after a re-referencing with `pop_reref` (including the output of (`[~, EEG] = evalc('pop_reref(EEG, [], ''exclude'', setdiff(1:EEG.nbchan, EEG.icachansind));');`), the field `.ref` is set to `'average'`, which is again not captured by `~strcmp(EEG.ref, 'averef')`. 

Is this a mistake and 3 different ways to denote a CAR ref?

**Comment by arnodelorme** [comment]
Fixed
