### ISSUE TITLE
error in pop_iclabel when data is average referenced

### ISSUE THREAD

**Issue by crisglav** [sccn/ICLabel#29]
I have performed an average reference in my data, therefore the field `EEG.ref = 'average'`. However after runing pop_ica and trying to run pop_iclabel I get an error in ICL_feature_extractor in line 15 because it compares the EEG.ref field to 'avgeref' instead of 'average'. 
https://github.com/sccn/ICLabel/blob/e8abc99e0c371ff49eff115cf7955fafc7f7969a/ICL_feature_extractor.m#L15

Could you update this field?
Best,
Cristina Gil

**Comment by arnodelorme** [comment]
Yes, updated. Thank you
