### ISSUE TITLE
rng(0)

### ISSUE THREAD

**Issue by EmmaRenauld** [sccn/ICLabel#3]
Matlab is stopping the process with following error:

            Error using rng (line 96)
            The current random number generator is the legacy generator.  This is because you have executed a command such as rand('state',0), which activates MATLAB's legacy random number behavior.  You may not use RNG to reseed the legacy random number generator.

             Use rng('default') to reinitialize the random number generator to its startup configuration, or call RNG using a specific generator type, such as rng(seed,'twister').

             Error in eeg_rpsd (line 20)
             rng(0)

It did not happen when I first ran ICLabel. But then I ran ICA (pop_runica) on a new dataset, tried to run ICLabel on it, and the error was shown. The same process was reproduced twice.

(Using Matlab R2016b)

**Comment by lucapton** [comment]
Thank you for the bug report. It should be fixed now. It will take a while for the update to make its way into the EEGLAB extension manager but you can manually update using git.
