### ISSUE TITLE
eeg_rpsd() line 38

### ISSUE THREAD

**Issue by af9246** [sccn/ICLabel#30]
When trying to run "tools --> classify components using ICLabel --> label components", after pop up menu and selecting default (or lite or beta), I get the following error message

![image](https://user-images.githubusercontent.com/111197310/184509678-219829f2-eeff-40fa-a8a5-7c0b142e6456.png)

**Comment by arnodelorme** [comment]
Closing this for now, but if you have a dataset to submit, it would be fantastic.
