### ISSUE TITLE
ICLabel fails badly with data with EEG.srate < 200

### ISSUE THREAD

**Issue by jiversen** [sccn/ICLabel#31]
It appears that ICLabel creates PSD features with max frequency 100 Hz, and thus needs data with sampling rate >= 200 Hz.

However, ICLabel is written to assume that the only way it could fail is if the model mex has not been compiled properly, and in this case recompiles the mex file, which is the wrong solution. Then it tries again and fails again, incorrectly warning that complication was unsuccessful, while it was in fact successful. 

In this case the model input is the problem, not the model. This is very confusing for the user.

Solution: add a check for EEG.state < 200, and error out informatively if so.

**Comment by arnodelorme** [comment]
Transfered to EEGLAB
