### ISSUE TITLE
A proposal of a solution to eeg_rpsd index error

### ISSUE THREAD

**Issue by eesimtmp** [sccn/ICLabel#32]
Dear all,
I have eeg files in edf format with different sampling frequencies.
For the EEG.srate = 200 ones, the Automagic runs without a hitch.
However, for the EEG.srate = 1000 ones, although runICA goes smoothly, but the ICLabel give the following error:
(eeg_rpsd.m, line 35, index in position 2 is invalid)
<img width="533" alt="Screen Shot 2023-02-24 at 1 51 32 PM" src="https://user-images.githubusercontent.com/126083032/221108494-efd9122c-e8d1-45a9-ad21-873a9f6099de.png">

I found that in the eeg_rpsd.m file, when EEG.srate is 1kHz, the n_points variable becomes 1E3, which is treated as a float rather than an integer, causing the subsequent indexing to fail.
A solution is proposed: add line 17 as shown in the next picture (n_points = round(n_points)
<img width="701" alt="Screen Shot 2023-02-24 at 2 26 11 PM" src="https://user-images.githubusercontent.com/126083032/221109230-28944d47-5d79-4fb5-9d8a-e31e7ea15776.png">
After that, IClabel runs as intended, but I am curious if this solution breaks anything.

Sincerely yours,
Edward Cheng.

**Comment by arnodelorme** [comment]
I think floor is a better choice. I have added it to the code at 49a38e4
