### ISSUE TITLE
Possible mis-classification?

### ISSUE THREAD

**Issue by soul-M-42** [sccn/ICLabel#33]
Im not very sure but it just cannot make sense to me why this component is tagged as Brain signal dispite Eye with even 69% confidence......
![无标题](https://github.com/sccn/ICLabel/assets/37969642/77fa7612-53f2-4981-9e60-9ea9bfcfd85c)

**Comment by arnodelorme** [comment]
Indeed. Please upload dataset for further investagation.

**Comment by arnodelorme** [comment]
This has been fixed in IClabel v1.6
