### ISSUE TITLE
Undefined function 'fir_filterdcpadded' for input arguments of type 'double.'

### ISSUE THREAD

**Issue by metoeeg** [sccn/ICLabel#6]
![ICLABEL_error](https://user-images.githubusercontent.com/63247916/78572492-d4f36500-7827-11ea-8ead-360629fc131b.png)

Hello,

I receive this error when I want to run ICLabel. I've been struggling to fix it. Any help would be appreciated. Thanks!

**Comment by lucapton** [comment]
Hi @metoeeg, I realize you had your question answered on the EEGLABlist long ago, but I'll answer it here for posterity.

This problem occurs when you clone the git repo without using the --recursive flag. You can either  get the plugin from the EEGLAB plugin manager or clone it again from here including the --recursive flag.
