### ISSUE TITLE
Labels remain after components are removed

### ISSUE THREAD

**Issue by JohnAtl** [sccn/ICLabel#8]
When components are removed, labels remain and are invalid. The labels still reflect the values of the prior component numbers.

<img width="1602" alt="Screen Shot 2020-05-14 at 11 07 47 AM" src="https://user-images.githubusercontent.com/5720074/81952498-8ed2b380-95d4-11ea-8849-1e41dfa665c9.png">

**Comment by lucapton** [comment]
Thanks for pointing this out.  I've thought about the issue before but didn't have a good solution. Now that I consider it again, perhaps label validity could be checked against a hash of EEG.icawinv. What you do you think about that @arnodelorme?

**Comment by arnodelorme** [comment]
I think pop_runica should remove labels when components are removed. I have modified pop_runica.

Arno

**Comment by JohnAtl** [comment]
If one uses iclabel() then pop_icflag(), then pop_subcomp() to remove 
the bad components, then looks at the components using pop_viewprops(), 
the labels left behind are misleading.
Ideally, pop_subcomp() would remove the labels of components that are 
removed, or if that isn't practical, remove all labels.

Regards,
John

**Comment by arnodelorme** [comment]
Yes, pop_subcomp() needs to be updated to remove the components as well. I have updated it and changed the zip file.
